#!/usr/bin/env python3
"""Tests for deterministic, non-overwriting Scene Evidence Markdown rendering."""

from __future__ import annotations

import contextlib
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = SKILL_ROOT.parents[1]
sys.path.insert(0, str(SKILL_ROOT / "scripts"))

from render_scene_evidence import (  # noqa: E402
    EVIDENCE_ROOT,
    GENERATED_SUFFIX,
    build_render_snapshot,
    discover_sources,
    extract_render_snapshot,
    generated_path,
    load_evidence,
    main,
    render_evidence,
    render_snapshot,
)


class SceneEvidenceRendererTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.sources = discover_sources()
        cls.source = cls.sources[0]
        cls.evidence = load_evidence(cls.source)

    def test_current_corpus_has_thirty_one_canonical_sources(self) -> None:
        self.assertEqual(len(self.sources), 31)

    def test_render_is_deterministic_and_round_trips_displayed_facts(self) -> None:
        first = render_evidence(self.evidence)
        second = render_evidence(self.evidence)
        self.assertEqual(first, second)
        snapshot = extract_render_snapshot(first)
        self.assertEqual(snapshot, build_render_snapshot(self.evidence))
        self.assertEqual(render_snapshot(snapshot), first)

    def test_render_contains_required_human_review_sections(self) -> None:
        rendered = render_evidence(self.evidence)
        for section in (
            "## Summary",
            "## Scene problem",
            "## Statistics",
            "## Shots",
            "## Candidate-rule lineage",
            "## UNKNOWN register",
            "## Boundary evidence",
            "## Validation warnings",
        ):
            self.assertIn(section, rendered)
        self.assertIn("Do not edit this file by hand", rendered)

    def test_generated_path_never_collides_with_legacy_markdown(self) -> None:
        destination = generated_path(self.source)
        self.assertTrue(destination.name.endswith(GENERATED_SUFFIX))
        self.assertNotEqual(destination, self.source.with_suffix(".md"))
        legacy = self.source.with_name(
            self.source.name.removesuffix(".scene-evidence.json") + ".md"
        )
        self.assertNotEqual(destination, legacy)

    def test_cli_output_root_preserves_all_existing_markdown(self) -> None:
        legacy_markdown = [
            path
            for path in EVIDENCE_ROOT.rglob("*.md")
            if not path.name.endswith(GENERATED_SUFFIX)
        ]
        before = {path: path.read_bytes() for path in legacy_markdown}
        with tempfile.TemporaryDirectory() as directory:
            output_root = Path(directory)
            with contextlib.redirect_stdout(io.StringIO()):
                self.assertEqual(main(["--output-root", str(output_root)]), 0)
            rendered = sorted(output_root.rglob(f"*{GENERATED_SUFFIX}"))
            self.assertEqual(len(rendered), 31)
            with contextlib.redirect_stdout(io.StringIO()):
                self.assertEqual(
                    main(["--output-root", str(output_root), "--check"]),
                    0,
                )
        self.assertEqual(
            before,
            {path: path.read_bytes() for path in legacy_markdown},
        )

    def test_check_reports_generated_drift(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output_root = Path(directory)
            with contextlib.redirect_stdout(io.StringIO()):
                self.assertEqual(
                    main([str(self.source), "--output-root", str(output_root)]),
                    0,
                )
            destination = generated_path(self.source, output_root)
            destination.write_text(
                destination.read_text(encoding="utf-8") + "manual drift\n",
                encoding="utf-8",
            )
            stderr = io.StringIO()
            with contextlib.redirect_stderr(stderr):
                self.assertEqual(
                    main(
                        [
                            str(self.source),
                            "--output-root",
                            str(output_root),
                            "--check",
                        ]
                    ),
                    1,
                )
            self.assertIn("DRIFT", stderr.getvalue())

    def test_stdout_mode_emits_one_complete_document(self) -> None:
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            self.assertEqual(main([str(self.source), "--stdout"]), 0)
        rendered = stdout.getvalue()
        self.assertEqual(
            json.loads(
                json.dumps(extract_render_snapshot(rendered), ensure_ascii=False)
            ),
            build_render_snapshot(self.evidence),
        )


if __name__ == "__main__":
    unittest.main()
